services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bizlab
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./files:/app/files
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - backend

volumes:
  mysql_data:

  