# Generated by Django 5.1.7 on 2025-05-15 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('salePrice', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('places', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=255)),
                ('secondName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('birthday', models.DateField()),
                ('role', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseId', to='BizLabApp.course')),
            ],
            options={
                'db_table': 'compounds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='BizLabApp.course')),
            ],
            options={
                'db_table': 'lessons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=1)),
                ('file', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='BizLabApp.lesson')),
            ],
            options={
                'db_table': 'materials',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BizLabApp.sale'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=255)),
                ('needToCheck', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprogress', to='BizLabApp.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonId', to='BizLabApp.lesson')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialID', to='BizLabApp.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId_userprogress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAndUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseId_courseanduser', to='BizLabApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId_courseanduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
