# Generated by Django 5.1.6 on 2025-05-14 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compoundCollections',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('collectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='BizLabApp.compoundcollection')),
            ],
            options={
                'db_table': 'compounds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('salePrice', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('places', models.IntegerField()),
                ('compoundCollection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BizLabApp.compoundcollection')),
                ('saleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BizLabApp.sale')),
            ],
            options={
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='compoundcollection',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_collections', to='BizLabApp.course'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='BizLabApp.course')),
            ],
            options={
                'db_table': 'lessons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=1)),
                ('file', models.CharField(max_length=255)),
                ('lessonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='BizLabApp.lesson')),
            ],
            options={
                'db_table': 'materials',
                'managed': True,
            },
        ),
    ]
