# Generated by Django 5.2.7 on 2025-11-06 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BizLabApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=1)),
                ('file', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs',
                'managed': True,
            },
        ),
    ]
